import Head from "next/head";
import React from "react";

export const metadata = {
	title: "Leave | Employee Portal",
	description: "Generated by create next app",
};

export default async function Page() {
	return (
		<>
			<div>Leave</div>
		</>
	);
}
