"use client";
import { createTheme } from "../../theme";
import "../globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import { styled } from "@mui/material/styles";
import { LeftNav } from "@/layouts/dashboard/left-nav";
import { TopNav } from "@/layouts/dashboard/top-nav";

const inter = Inter({ subsets: ["latin"] });

const SIDE_NAV_WIDTH = 300;

export const metadata = {
	title: "Employee Portal",
	description: "Generated by create next app",
};

const LayoutRoot = styled("div")(({ theme }) => ({
	display: "flex",
	flex: "1 1 auto",
	maxWidth: "100%",
	[theme.breakpoints.up("lg")]: {
		paddingLeft: SIDE_NAV_WIDTH,
	},
}));

const LayoutContainer = styled("div")({
	display: "flex",
	flex: "1 1 auto",
	flexDirection: "column",
	width: "100%",
});

const theme = createTheme();

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head />
			<body className={inter.className}>
				<ThemeProvider theme={theme}>
					<TopNav />
					<LeftNav />
					<LayoutRoot>
						<LayoutContainer>{children}</LayoutContainer>
					</LayoutRoot>
				</ThemeProvider>
			</body>
		</html>
	);
}
