import Head from "next/head";
import React from "react";

export const metadata = {
	title: "Signin | Employee Portal",
	description: "Generated by create next app",
};

export default async function Page() {
	return (
		<>
			<div>Durban Airways</div>
			<h2>Welcome to Durban Airways</h2>
		</>
	);
}
